org_id: "hospital-b"
app_id: "pharmacy"
org_display_name: "Hospital B"
app_display_name: "Pharmacy System"
org_reference: "https://fhir.hospital-b.example/fhir/Organization/HospitalB"
role: "fulfiller"
tenant: "fulfiller"
jwks_url: "https://hospital-b.example/.well-known/jwks/pharmacy.json"

required_scopes:
  - "system/Patient.r"
  - "system/MedicationStatement.r"

optional_scopes:
  - "system/ServiceRequest.r"
  - "system/AllergyIntolerance.r"
  - "system/Condition.r"
  - "system/Coverage.r"
  - "system/Practitioner.r"
