org_id: "hospital-b"
display_name: "Hospital B"
role: "fulfiller"
tenant: "fulfiller"
org_reference: "https://fhir.hospital-b.example/fhir/Organization/HospitalB"

apps:
  ris:
    display_name: "RIS"
    jwks_url: "http://jwks-server/fulfiller-l2.jwks.json"
    audiences:
      fhir-hospital-a:
        scopes:
          - "system/ServiceRequest.r"
          - "system/Patient.r"
          - "system/ImagingStudy.r"
          - "system/DiagnosticReport.r"
      fhir-hospital-c:
        scopes:
          - "system/Task.cru"
          - "system/Patient.r"
          - "system/Observation.r"
          - "system/Immunization.r"
      fhir-hospital-d:
        scopes:
          - "system/Patient.r"
          - "system/Condition.r"
          - "system/AllergyIntolerance.r"
          - "system/MedicationStatement.r"
      fhir-hospital-e:
        scopes:
          - "system/ServiceRequest.r"
          - "system/Patient.r"
          - "system/QuestionnaireResponse.cru"
      fhir-hospital-b:
        scopes:
          - "system/Practitioner.r"
          - "system/PractitionerRole.r"
          - "system/Organization.r"
