org_id: "hospital-d"
display_name: "Hospital D"
role: "fulfiller"
tenant: "fulfiller"
org_reference: "https://fhir.hospital-d.example/fhir/Organization/HospitalD"

apps:
  lab-system:
    display_name: "Laboratory System"
    jwks_url: "http://jwks-server/fulfiller-l2.jwks.json"
    audiences:
      fhir-hospital-a:
        scopes:
          - "system/ServiceRequest.r"
          - "system/Patient.r"
          - "system/Observation.r"
          - "system/DiagnosticReport.r"
      fhir-hospital-b:
        scopes:
          - "system/Task.cru"
          - "system/Patient.r"
          - "system/Condition.r"
          - "system/Coverage.r"
      fhir-hospital-c:
        scopes:
          - "system/ServiceRequest.r"
          - "system/Patient.r"
          - "system/AllergyIntolerance.r"
          - "system/MedicationStatement.r"
          - "system/Observation.r"
      fhir-hospital-e:
        scopes:
          - "system/Task.cru"
          - "system/ServiceRequest.r"
          - "system/Patient.r"
          - "system/QuestionnaireResponse.cru"
      fhir-hospital-d:
        scopes:
          - "system/Organization.r"
          - "system/Practitioner.r"
