client_id: "hospital_b-l2"
client_name: "Hospital B"
organization_reference: "https://fhir.hospital_b.example/fhir/Organization/HospitalB"
fhir_url: "https://fhir.hospital_b.example/fhir"
jwks_url: "http://jwks-server/.well-known/hospital_b-l2.jwks.json"
auth_level: "L2"
